Logging:
    default: INFO

General:
    Modus:         List
    Time_Step_Mode: None
    Delta_Time:    0.1
    End_Time:      10000.0    # make sure runtime is long enough for back-propagation
    Randomseed:    -1
    Nevents:       1000

Output:
    Particles:
        Format:          ["Binary", "Oscar2013"]

Modi:
    List:
        File_Directory: "."
        File_Prefix: "sampling"
        Shift_Id: 0
